namespace LibDerailer.IO.Elf.Dwarf2.Enums
{
    public enum Dwarf2Attribute
    {
        Sibling            = 0x01,
        Location           = 0x02,
        Name               = 0x03,
        Ordering           = 0x09,
        SubscrData         = 0x0a,
        ByteSize           = 0x0b,
        BitOffset          = 0x0c,
        BitSize            = 0x0d,
        ElementList        = 0x0f,
        StmtList           = 0x10,
        LowPc              = 0x11,
        HighPc             = 0x12,
        Language           = 0x13,
        Member             = 0x14,
        Discr              = 0x15,
        DiscrValue         = 0x16,
        Visibility         = 0x17,
        Import             = 0x18,
        StringLength       = 0x19,
        CommonReference    = 0x1a,
        CompDir            = 0x1b,
        ConstValue         = 0x1c,
        ContainingType     = 0x1d,
        DefaultValue       = 0x1e,
        Inline             = 0x20,
        IsOptional         = 0x21,
        LowerBound         = 0x22,
        Producer           = 0x25,
        Prototyped         = 0x27,
        ReturnAddr         = 0x2a,
        StartScope         = 0x2c,
        BitStride          = 0x2e /* DWARF3 name */,
        StrideSize         = 0x2e /* DWARF2 name */,
        UpperBound         = 0x2f,
        AbstractOrigin     = 0x31,
        Accessibility      = 0x32,
        AddressClass       = 0x33,
        Artificial         = 0x34,
        BaseTypes          = 0x35,
        CallingConvention  = 0x36,
        Count              = 0x37,
        DataMemberLocation = 0x38,
        DeclColumn         = 0x39,
        DeclFile           = 0x3a,
        DeclLine           = 0x3b,
        Declaration        = 0x3c,
        DiscrList          = 0x3d,
        Encoding           = 0x3e,
        External           = 0x3f,
        FrameBase          = 0x40,
        Friend             = 0x41,
        IdentifierCase     = 0x42,
        MacroInfo          = 0x43,
        NamelistItem       = 0x44,
        Priority           = 0x45,
        Segment            = 0x46,
        Specification      = 0x47,
        StaticLink         = 0x48,
        Type               = 0x49,
        UseLocation        = 0x4a,
        VariableParameter  = 0x4b,
        Virtuality         = 0x4c,
        VtableElemLocation = 0x4d,
        Allocated          = 0x4e /* DWARF3 */,
        Associated         = 0x4f /* DWARF3 */,
        DataLocation       = 0x50 /* DWARF3 */,
        ByteStride         = 0x51 /* DWARF3f */,
        Stride             = 0x51 /* DWARF3 (do not use) */,
        EntryPc            = 0x52 /* DWARF3 */,
        UseUtf8            = 0x53 /* DWARF3 */,
        Extension          = 0x54 /* DWARF3 */,
        Ranges             = 0x55 /* DWARF3 */,
        Trampoline         = 0x56 /* DWARF3 */,
        CallColumn         = 0x57 /* DWARF3 */,
        CallFile           = 0x58 /* DWARF3 */,
        CallLine           = 0x59 /* DWARF3 */,
        Description        = 0x5a /* DWARF3 */,
        BinaryScale        = 0x5b /* DWARF3f */,
        DecimalScale       = 0x5c /* DWARF3f */,
        Small              = 0x5d /* DWARF3f */,
        DecimalSign        = 0x5e /* DWARF3f */,
        DigitCount         = 0x5f /* DWARF3f */,
        PictureString      = 0x60 /* DWARF3f */,
        Mutable            = 0x61 /* DWARF3f */,
        ThreadsScaled      = 0x62 /* DWARF3f */,
        Explicit           = 0x63 /* DWARF3f */,
        ObjectPointer      = 0x64 /* DWARF3f */,
        Endianity          = 0x65 /* DWARF3f */,
        Elemental          = 0x66 /* DWARF3f */,
        Pure               = 0x67 /* DWARF3f */,
        Recursive          = 0x68 /* DWARF3f */,
        Signature          = 0x69 /* DWARF4 */,
        MainSubprogram     = 0x6a /* DWARF4 */,
        DataBitOffset      = 0x6b /* DWARF4 */,

        ConstExpr = 0x6c /* DWARF4 */
/* In extensions, we attempt to include the vendor extension
   in the name even when the vendor leaves it out. */
/* HP extensions. */,
        HpBlockIndex = 0x2000 /* HP */
/* Follows extension so dwarfdump prints the most-likely-useful name. */,
        LoUser                    = 0x2000,
        MipsFde                   = 0x2001 /* MIPS/SGI */,
        MipsLoopBegin             = 0x2002 /* MIPS/SGI */,
        MipsTailLoopBegin         = 0x2003 /* MIPS/SGI */,
        MipsEpilogBegin           = 0x2004 /* MIPS/SGI */,
        MipsLoopUnrollFactor      = 0x2005 /* MIPS/SGI */,
        MipsSoftwarePipelineDepth = 0x2006 /* MIPS/SGI */,
        MipsLinkageName           = 0x2007 /* MIPS/SGI, GNU, and others.*/,
        MipsStride                = 0x2008 /* MIPS/SGI */,
        MipsAbstractName          = 0x2009 /* MIPS/SGI */,
        MipsCloneOrigin           = 0x200a /* MIPS/SGI */,
        MipsHasInlines            = 0x200b /* MIPS/SGI */,
        MipsStrideByte            = 0x200c /* MIPS/SGI */,
        MipsStrideElem            = 0x200d /* MIPS/SGI */,
        MipsPtrDopetype           = 0x200e /* MIPS/SGI */,
        MipsAllocatableDopetype   = 0x200f /* MIPS/SGI */,
        MipsAssumedShapeDopetype  = 0x2010 /* MIPS/SGI */,
        MipsAssumedSize           = 0x2011 /* MIPS/SGI */
/* HP extensions. */,
        HpUnmodifiable           = 0x2001 /* conflict: MIPS */,
        HpActualsStmtList        = 0x2010 /* conflict: MIPS */,
        HpProcPerSection         = 0x2011 /* conflict: MIPS */,
        HpRawDataPtr             = 0x2012 /* HP */,
        HpPassByReference        = 0x2013 /* HP */,
        HpOptLevel               = 0x2014 /* HP */,
        HpProfVersionId          = 0x2015 /* HP */,
        HpOptFlags               = 0x2016 /* HP */,
        HpColdRegionLowPc        = 0x2017 /* HP */,
        HpColdRegionHighPc       = 0x2018 /* HP */,
        HpAllVariablesModifiable = 0x2019 /* HP */,
        HpLinkageName            = 0x201a /* HP */,
        HpProfFlags              = 0x201b /* HP */,
        CpqDiscontigRanges       = 0x2001 /* COMPAQ/HP */,
        CpqSemanticEvents        = 0x2002 /* COMPAQ/HP */,
        CpqSplitLifetimesVar     = 0x2003 /* COMPAQ/HP */,
        CpqSplitLifetimesRtn     = 0x2004 /* COMPAQ/HP */,
        CpqPrologueLength        = 0x2005 /* COMPAQ/HP */,
        IntelOtherEndian         = 0x2026 /* Intel, 1 if byte swapped. */
/* GNU extensions. */,
        SfNames   = 0x2101 /* GNU */,
        SrcInfo   = 0x2102 /* GNU */,
        MacInfo   = 0x2103 /* GNU */,
        SrcCoords = 0x2104 /* GNU */,
        BodyBegin = 0x2105 /* GNU */,
        BodyEnd   = 0x2106 /* GNU */,
        GnuVector = 0x2107 /* GNU */
/* ALTIUM extension: ALTIUM Compliant location lists (flag) */,
        AltiumLoclist = 0x2300 /* ALTIUM  */
/* Sun extensions */,
        SunTemplate             = 0x2201 /* SUN */,
        VmsRtnbegPdAddress      = 0x2201 /* VMS */,
        SunAlignment            = 0x2202 /* SUN */,
        SunVtable               = 0x2203 /* SUN */,
        SunCountGuarantee       = 0x2204 /* SUN */,
        SunCommandLine          = 0x2205 /* SUN */,
        SunVbase                = 0x2206 /* SUN */,
        SunCompileOptions       = 0x2207 /* SUN */,
        SunLanguage             = 0x2208 /* SUN */,
        SunBrowserFile          = 0x2209 /* SUN */,
        SunVtableAbi            = 0x2210 /* SUN */,
        SunFuncOffsets          = 0x2211 /* SUN */,
        SunCfKind               = 0x2212 /* SUN */,
        SunVtableIndex          = 0x2213 /* SUN */,
        SunOmpTprivAddr         = 0x2214 /* SUN */,
        SunOmpChildFunc         = 0x2215 /* SUN */,
        SunFuncOffset           = 0x2216 /* SUN */,
        SunMemopTypeRef         = 0x2217 /* SUN */,
        SunProfileId            = 0x2218 /* SUN */,
        SunMemopSignature       = 0x2219 /* SUN */,
        SunObjDir               = 0x2220 /* SUN */,
        SunObjFile              = 0x2221 /* SUN */,
        SunOriginalName         = 0x2222 /* SUN */,
        SunHwcprofSignature     = 0x2223 /* SUN */,
        SunAmd64Parmdump        = 0x2224 /* SUN */,
        SunPartLinkName         = 0x2225 /* SUN */,
        SunLinkName             = 0x2226 /* SUN */,
        SunPassWithConst        = 0x2227 /* SUN */,
        SunReturnWithConst      = 0x2228 /* SUN */,
        SunImportByName         = 0x2229 /* SUN */,
        SunF90Pointer           = 0x222a /* SUN */,
        SunPassByRef            = 0x222b /* SUN */,
        SunF90Allocatable       = 0x222c /* SUN */,
        SunF90AssumedShapeArray = 0x222d /* SUN */,
        SunCVla                 = 0x222e /* SUN */,
        SunReturnValuePtr       = 0x2230 /* SUN */,
        SunDtorStart            = 0x2231 /* SUN */,
        SunDtorLength           = 0x2232 /* SUN */,
        SunDtorStateInitial     = 0x2233 /* SUN */,
        SunDtorStateFinal       = 0x2234 /* SUN */,
        SunDtorStateDeltas      = 0x2235 /* SUN */,
        SunImportByLname        = 0x2236 /* SUN */,
        SunF90UseOnly           = 0x2237 /* SUN */,
        SunNamelistSpec         = 0x2238 /* SUN */,
        SunIsOmpChildFunc       = 0x2239 /* SUN */,
        SunFortranMainAlias     = 0x223a /* SUN */,
        SunFortranBased         = 0x223b /* SUN */
/* UPC extension */,
        UpcThreadsScaled = 0x3210 /* UPC */
/* PGI (STMicroelectronics) extensions. */,

        PgiLbase =
            0x3a00 /* PGI. Block, constant, reference. This attribute is an ASTPLAB extension used to describe the array local base.  */,

        PgiSoffset =
            0x3a01 /* PGI. Block, constant, reference. ASTPLAB adds this attribute to describe the section offset, or the offset to the first element in the dimension. */,

        PgiLstride =
            0x3a02 /* PGI. Block, constant, reference. ASTPLAB adds this attribute to describe the linear stride or the distance between elements in the dimension. */

/* Apple Extensions for closures  */,
        AppleClosure = 0x3fe4 /* Apple */
/* Apple Extensions for Objective-C runtime info */,
        AppleMajorRuntimeVers = 0x3fe5 /* Apple */,
        AppleRuntimeClass     = 0x3fe6 /* Apple */,

        HiUser = 0x3fff
    }
}